### ISSUE TITLE
API compatibility with request_store

### ISSUE THREAD

**Issue by saturnflyer** [ElMassimo/request_store_rails#3]
I'm curious if you'd be interested in a pull request to make this api compatible with request_store.

I'm trying to use it with ahoy and have an open PR over there to be able to use this instead of request_store https://github.com/ankane/ahoy/pull/129
I realized recently that the API of request_store has diverged a bit from this.

Has anyone working on request_store_rails reached out to the maintainers of request_store to find out if they are interested in merging the features from this project into that one?

**Comment by ElMassimo** [comment]
Interesting. One of the goals of this library was to make it easy to switch from [`request_store`](https://github.com/steveklabnik/request_store) if the threading limitation was an issue, but I never ensured the API was fully compatible.

Haven't reached out to the maintainers of `request_store`, I don't think they would be willing to merge the features in this library for two reasons:
- The problem this library tackles is not as common.
- The implementation requires an additional dependency, `concurrent-ruby`.

Would happily take a pull request to implement the methods added in https://github.com/steveklabnik/request_store/pull/49, and anything else that might be necessary to ensure compatibility. If I understand correctly, the public API would add `RequestLocals.active?`, and it would require some changes in the middleware as well.

**Comment by saturnflyer** [comment]
I'm still wrapping my head around all of this. But concurrent-ruby is a dependency of activesupport 5 and version 4 uses the thread_safe gem which has the ThreadSafe::Cache that request_store_rails requires

**Comment by ElMassimo** [comment]
Current version of `request_store_rails` uses `Concurrent::Map`, the update happened in #1 😃

**Comment by saturnflyer** [comment]
Ah. I missed that. Thanks.
A merge still might be possible given rails 5 dependency changes

**Comment by ElMassimo** [comment]
Should be closed by #5, though there's always a chance of API differences on new releases of `request_store`.
