### ISSUE TITLE
wrong argument type Integer (expected Proc)

### ISSUE THREAD

**Issue by silva96** [ElMassimo/request_store_rails#6]
```
class ApplicationController < ActionController::Base

before_action :set_request_locals

def set_request_locals
    RequestLocals.store[:request] = request
    RequestLocals.store[:current_agency] = current_agency
end
```

Then calling this in a model.

`current_agency = RequestLocals[:current_agency]`

... Some times (very few times) it raises wrong argument type Integer (expected Proc)

in
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:228 in []

**Comment by silva96** [comment]
related to a bug in ruby 2.4.0

https://bugs.ruby-lang.org/issues/13107

**Comment by ElMassimo** [comment]
Thanks for the report, keeping it open in case anyone comes up with a workaround.
