### ISSUE TITLE
Any reason to not always generate a random request_id in middleware?

### ISSUE THREAD

**Issue by gtmax** [ElMassimo/request_store_rails#9]
In https://github.com/ElMassimo/request_store_rails/blob/master/lib/request_store_rails/middleware.rb#L27 `env['action_dispatch.request_id'] || env['HTTP_X_REQUEST_ID']` are used as the base for request_id - why not always generate a random one? Using the forwarded request_id seems to allow room for accidentally sharing the RequestLocals, e.g. in a scenario of a multi-threaded web server that makes another request with forwarded request_id which ends up being processed on the same server instance.

**Comment by ElMassimo** [comment]
Some applications benefit from sharing the cache across requests with the same id that are being handled concurrently, but I agree it would be safer not to rely on the request id provided by the [`ActionDispatch::RequestId`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/request_id.rb#L7-L16) middleware, which might be useful for tracing purposes but leaves room for accidents in this use case.

Will cut a new release that uses `SecureRandom.uuid` instead.

Thanks for the suggestion!
